theme: jekyll-theme-cayman
title: Power BI Portfolio – Saurabh Khosla
description: "A data-driven portfolio of projects in analytics, customer ops, and e-commerce — built using Power BI, Tableau & Excel."
---
github:
  is_project_page: false
  show_downloads: false
